In [1]:

import numpy as np
import pandas as pd

# 1
arr = np.arange(6)
print("Q1:", arr.dtype)

# 2
print("Q2:", arr.dtype == np.float64)

# 3
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print("Q3:", arr)

# 4
arr = np.array([1, 2, 3])
arr_float = arr.astype(np.float32)
print("Q4:", arr_float)

# 5
arr = np.array([1.123456789], dtype=np.float64)
arr_reduced = arr.astype(np.float32)
print("Q5:", arr_reduced)

# 6
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

# 7
def array_dimension(arr):
    return arr.ndim

# 8
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

# 9
def array_strides(arr):
    return arr.strides

# 10
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

# 11
def create_zeros_array(n):
    return np.zeros(n)

# 12
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

# 13
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

# 14
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

# 15
def create_identity_matrix(n):
    return np.eye(n)

# 16
def list_to_array(lst):
    return np.array(lst)

# 17
arr = np.array([1, 2, 3])
arr_view = arr.view()
print("Q17:", arr_view)

# 18
def concatenate_arrays(a, b, axis=0):
    return np.concatenate((a, b), axis=axis)

# 19
a = np.array([[1], [2]])
b = np.array([[3, 4]])
print("Q19:", np.concatenate((a, b.T), axis=1))

# 20
def stack_vertically(arrays):
    return np.vstack(arrays)

# 21
def generate_array_in_range(start, stop, step):
    return np.arange(start, stop+1, step)

# 22
print("Q22:", np.linspace(0, 1, 10))

# 23
print("Q23:", np.logspace(0, 3, 5))

# 24
df = pd.DataFrame(np.random.randint(1, 101, size=(5, 3)))
print("Q24:\n", df)

# 25
def replace_negatives_with_zero(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

# 26
arr = np.array([10, 20, 30, 40, 50])
print("Q26:", arr[2])

# 27
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Q27:", arr2d[1, 2])

# 28
print("Q28:", arr[arr > 5])

# 29
print("Q29:", arr[2:6])

# 30
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Q30:", arr2d[[0,1],[2,2]])

# 31
def extract_with_indices(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

# 32
def filter_greater_than(arr, threshold):
    return arr[arr > threshold]

# 33
def extract_3d_elements(arr, idx1, idx2, idx3):
    return arr[idx1, idx2, idx3]

# 34
def double_condition(arr, cond1, cond2):
    return arr[cond1 & cond2]

# 35
def extract_by_row_col(arr, rows, cols):
    return arr[rows, cols]

# 36
arr = np.array([1, 2, 3])
print("Q36:", arr + 5)

# 37
a = np.ones((3, 4))
b = np.array([[1], [2], [3]])
print("Q37:\n", a * b)

# 38
a = np.ones((4, 3))
b = np.array([[1, 2, 3, 4]]).T
print("Q38:\n", a + b)

# 39
a = np.ones((3, 1))
b = np.ones((1, 3))
print("Q39:\n", a + b)

# 40
print("Q40:", "Incompatible shapes")

# 41
arr2d = np.array([[1,2,3],[4,5,6]])
print("Q41:", arr2d.mean(axis=0))

# 42
print("Q42:", arr2d.max(axis=1))

# 43
print("Q43:", np.argmax(arr2d, axis=0))

# 44
def moving_sum(arr):
    return np.cumsum(arr, axis=1)

# 45
def all_even_columns(arr):
    return np.all(arr % 2 == 0, axis=0)

# 46
def reshape_array(arr, m, n):
    return arr.reshape((m, n))

# 47
def flatten_array(arr):
    return arr.flatten()

# 48
def concat_along_axis(a, b, axis):
    return np.concatenate((a, b), axis=axis)

# 49
def split_array(arr, indices, axis=0):
    return np.split(arr, indices, axis=axis)

# 50
def insert_delete(arr, insert_idx, insert_val, delete_idx):
    arr = np.insert(arr, insert_idx, insert_val)
    arr = np.delete(arr, delete_idx)
    return arr

# 51 - 55
def elementwise_operations(arr1, arr2):
    return arr1+arr2, arr1-arr2, arr1*arr2, arr1/arr2, arr1**arr2

# 56
def count_substring(arr, substring):
    return np.char.count(arr, substring)

# 57
def extract_uppercase(arr):
    return np.char.upper(arr)

# 58
def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)

# 59
def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

# 60
def longest_string_length(arr):
    return max(len(s) for s in arr)

# 61
data = np.random.randint(1, 1001, 100)
print("Q61:", np.mean(data), np.median(data), np.var(data), np.std(data))

# 62
data = np.random.randint(1, 101, 50)
print("Q62:", np.percentile(data, [25, 75]))

# 63
a = np.random.rand(10)
b = np.random.rand(10)
print("Q63:", np.corrcoef(a, b))

# 64
print("Q64:", np.dot([[1, 2]], [[3], [4]]))

# 65
arr = np.random.randint(1, 101, 50)
print("Q65:", np.percentile(arr, [10, 50, 90]))

# 66
def find_index(arr, element):
    return np.where(arr == element)

# 67
def sort_array(arr):
    return np.sort(arr)

# 68
def filter_gt_20(arr):
    return arr[arr > 20]

# 69
def filter_divisible_by_3(arr):
    return arr[arr % 3 == 0]

# 70
def filter_between(arr, low, high):
    return arr[(arr >= low) & (arr <= high)]

# 71
def check_byte_order(arr):
    return arr.dtype.byteorder

# 72
def inplace_byteswap(arr):
    arr.byteswap(inplace=True)
    return arr


Q1: int32
Q2: False
Q3: [1.+2.j 3.+4.j 5.+6.j]
Q4: [1. 2. 3.]
Q5: [1.1234568]
Q17: [1 2 3]
Q19: [[1 3]
 [2 4]]
Q22: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Q23: [   1.            5.62341325   31.6227766   177.827941   1000.        ]
Q24:
     0    1   2
0   3   57  94
1  60   28  43
2  93   17  93
3  59    1   8
4  95  100  83
Q26: 30
Q27: 6
Q28: [10 20 30 40 50]
Q29: [30 40 50]
Q30: [3 6]
Q36: [6 7 8]
Q37:
 [[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]
Q38:
 [[2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]]
Q39:
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
Q40: Incompatible shapes
Q41: [2.5 3.5 4.5]
Q42: [3 6]
Q43: [1 1 1]
Q61: 516.19 502.5 77580.69390000001 278.53311095810494
Q62: [27.   75.75]
Q63: [[ 1.         -0.25558455]
 [-0.25558455  1.        ]]
Q64: [[11]]
Q65: [13.9 47.  87. ]
